### ISSUE TITLE
os.chdir není potřeba

### ISSUE THREAD

**Issue by xtompok** [benesad/ukol_2#8]
Je očekávané, že program hledá vstupní soubory tam, odkud ho volám a ne tam, kde fyzicky sídlí. Ale pokud je to pro Tvůj vývoj pohodlnější, tak to klidně můžeš nechat, obě varianty jsou v souladu se zadáním.

**Comment by benesad** [comment]
Bylo to kvůli tomu, že jsem měl bordel v adresářích ze začátku.
